<?php

namespace Epilgrim\CurrencyConverterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends EntityRepository
{
    public function getAll(){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('r', 'c')
            ->from('Epilgrim\CurrencyConverterBundle\Entity\CurrencyRate', 'r')
                ->innerJoin('r.currency', 'c')
            ->orderBy('r.dateFrom');

        return $qb->getQuery()->getResult();
    }

    public function findByCodeAndDate($code, $date){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('r', 'c')
            ->from('Epilgrim\CurrencyConverterBundle\Entity\CurrencyRate', 'r')
                ->innerJoin('r.currency', 'c')
            ->where('c.code = :code')
                ->andWhere('r.dateFrom <= :date')
                ->andWhere('r.dateTo > :date')
            ->setParameter('code', $code)
            ->setParameter('date', $date);
        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
