<?php

namespace Epilgrim\CurrencyConverterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends EntityRepository
{
	public function getAll(){
	    $qb = $this->_em->createQueryBuilder();
	    $qb->select('c', 'r')
	        ->from('Epilgrim\CurrencyConverterBundle\Entity\Currency', 'c')
	        ->innerJoin('c.rates', 'r')
	        ->orderBy('r.dateFrom');

	    return $qb->getQuery()->getResult();
	}
}
